Added json schema validation and test
prefapp/action-make-state-repos-dispatches pull request #64
Opened 2024-10-15 11:59 UTC by JulianGV21

Closes #2

2024-10-15 13:30 UTC, alambike requested changes

2024-10-15 13:30 UTC, alambike commented on package.json
> +    "js-yaml": "^4.1.0",
Already yaml dependency included

2024-10-15 13:30 UTC, alambike commented on schema/jsonschema.json
> +              "additionalProperties": true
```suggestion
              "additionalProperties": false
```

All properties should be controlled by the json schema, not additional properties allowed

2024-10-15 13:30 UTC, alambike commented on validation.js
> +}
This is a test file, you don't need to do a process exit!

We are using Jest to create the tests cases: https://jestjs.io/es-ES/

You must define a tests case and use `expect` to validate the expected results, and the tests will pass or fail according to the results of the expected evaluation. 

See for example: https://github.com/prefapp/action-make-state-repos-dispatches/blob/f7a81d0ed6282a95f0c83f485789050aa701a057/__tests__/dispatcher.test.js#L75-L84

2024-10-17 12:30 UTC, alambike approved these changes

2024-10-17 20:11 UTC, alambike requested changes

2024-10-17 20:11 UTC, alambike commented on schema/jsonschema.json
Looks good but it needs to be used when loading the config file: https://github.com/prefapp/action-make-state-repos-dispatches/blob/main/utils/text-helper.js

2024-10-21 10:07 UTC, alambike commented on utils/validate.js
> +function ConfigParse(fileContent, encoding = '') {
```suggestion
function configParse(fileContent, encoding = '') {
```

2024-10-21 10:07 UTC, alambike commented on utils/validate.js
> +  ConfigParse
```suggestion
  configParse
```

2024-10-21 10:07 UTC, alambike commented on validation.test.js
> +const { ConfigParse } = require('./utils/validate')
```suggestion
const { configParse } = require('./utils/validate')
```

2024-10-21 10:07 UTC, alambike commented on validation.test.js
> +      ConfigParse(yaml.stringify(yamlWithoutRequiredField))
```suggestion
      configParse(yaml.stringify(yamlWithoutRequiredField))
```

2024-10-21 10:08 UTC, alambike commented on utils/validate.js
> +function ConfigParse(fileContent, encoding = '') {
Please, take a look to the style guide we use to follow: https://google.github.io/styleguide/jsguide.html#naming-rules-common-to-all-identifiers

2024-10-22 10:01 UTC, alambike approved these changes

2024-10-22 10:01 UTC, juanjosevazquezgil approved these changes

2024-10-22 10:01 UTC, merged